package com.generali.domain;
// Generated Mar 8, 2016 5:38:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 * 
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String oib;
     private String street;
     private String HNum;
     private String city;
     private Date birthDate;

    public User() {
    }

    public User(String name, String surname, String oib, String street, String HNum, String city, Date birthDate) {
       this.name = name;
       this.surname = surname;
       this.oib = oib;
       this.street = street;
       this.HNum = HNum;
       this.city = city;
       this.birthDate = birthDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getOib() {
        return this.oib;
    }
    
    public void setOib(String oib) {
        this.oib = oib;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getHNum() {
        return this.HNum;
    }
    
    public void setHNum(String HNum) {
        this.HNum = HNum;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }




}


